<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV5ac1ti\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV5ac1ti/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerV5ac1ti.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerV5ac1ti\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerV5ac1ti\appProdProjectContainer([
    'container.build_hash' => 'V5ac1ti',
    'container.build_id' => '67d5002b',
    'container.build_time' => 1637428110,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV5ac1ti');
