<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDfrsg4n\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDfrsg4n/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDfrsg4n.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDfrsg4n\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDfrsg4n\appProdProjectContainer([
    'container.build_hash' => 'Dfrsg4n',
    'container.build_id' => '9c1227b2',
    'container.build_time' => 1637428159,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDfrsg4n');
